config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources  :users,       only: [:new, :create, :show]
  resources  :sessions,    only: [:new, :create, :destroy]
  resources  :events,      only: [:index,:new, :create, :show]
  resources  :attendances, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator ,    class_name: "User"
  has_many   :attendances, foreign_key: "attended_event"
  has_many   :attendees, through: :attendances, source: "attendee"

  scope :past,     -> { where("event_date <  :today",
                              {today: Time.zone.now}).order(:event_date) }
  scope :upcoming, -> { where("event_date >= :today",
                              {today: Time.zone.now}).order(:event_date) }

  validates  :description, presence: true
  validates  :location,    presence: true
  validates  :event_date,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :hostings, class_name: "Event", foreign_key: "creator_id"
  has_many  :attendances, foreign_key: "attendee"
  has_many  :attended_events, through: :attendances

  def upcoming_events
    self.attended_events.where("event_date >= :today", { today: Time.zone.now })
  end

  def previous_events
    self.attended_events.where("event_date < :today", { today: Time.zone.now })
  end

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def log_in(user)
    session[:id] = user.id
    current_user
  end

  def current_user
    @current_user ||= User.find(session[:id])
  end

  def current_user=(user)
    @current_user = user
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
  end
  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      flash[:success] = "Your attendance was taken"
      redirect_to event_path(params[:attendance][:attended_event_id])
    else
      flash.now[:danger] = "Oh no! Something went wrong!"
      render event_path(params[:attendance][:attended_event_id])
    end
  end

  private
    def attendance_params
      params.require(:attendance).permit(:attendee_id,:attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, except: [:index, :show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new()
  end

  def create
    user = User.find(session[:id])
    @event = user.hostings.build(event_params)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to user
    else
      flash[:danger] = "Event was not created!"
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendance = @event.attendances.build(attendee_id: session[:id])
    @hosting = hosting?
    @attending = attending?
  end

  private
    def event_params
      params.require(:event).permit(:description, :location, :event_date)
    end

    def logged_in?
      redirect_to new_session_path if session[:id].nil?
    end

    def hosting?
      @event.creator_id == session[:id]
    end

    def attending?
      @event.attendees.pluck(:attendee_id).include?(session[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:sessions][:username])
    if @user
      log_in @user
      redirect_to @user
    else
      flash[:danger] = "Username not found!"
      render 'new'
    end
  end

  def destroy
    session[:id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been created!"
      log_in(@user)
      redirect_to root_path
    else
      flash.now[:danger] = "Your account was not saved!"
      render new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.previous_events
  end

  private
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_new.html.erb
<%= form_for(@attendance) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  
  <%= f.text_field :attended_event_id, type: :hidden %>


  <%= f.text_field :attendee_id, type: :hidden %>

  <%= f.submit "Attend" %>

<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<% if !session[:id].nil? %>
  <%= link_to "Host an event", new_event_path %>
<% end %>

<h1>List of events:</h1>
<%= link_to "Upcoming events", "#event_upcoming" %>
<%= link_to "Past events", "#event_past" %>
<h2 id="event_upcoming">Upcoming events</h2>
<% @events.upcoming.each do |event| %>
  <h3><%= link_to event.description, event_path(event) %></h3>
  <p>on: <%= event.event_date %></p>
<% end %>
<br>
<h2 id="event_past">Past events</h2>
<% @events.past.each do |event| %>
  <h3><%= link_to event.description, event_path(event) %></h3>
  <p>on: <%= event.event_date %></p>
<% end %>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :event_date %>
  <%= f.date_field :event_date %>


  <%= f.submit "Create Event" %>

<% end %>

app/views/events/show.html.erb
<h1><%= @event.description %></h1>
<p>hosted by: <%= @event.creator.username %></p>
<p><%= @event.attendances.count %> are attending:</p>

<%= render 'attendances/new'  unless session[:id].nil? || @hosting || @attending %>
<ul>
  <% @event.attendees.pluck(:username).each do |attendee| %>
    <li><%= attendee %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/header' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<%= link_to "Home", root_path %>
<% if session[:id].nil? %>
  <%= link_to "Sign in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% else %>
  <%= link_to "profile",  user_path(session[:id]) %>
  <%= link_to "Sign out", session_path(session[:id]) , method: "delete"%>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.submit "Create Account" %>

<% end %>

app/views/users/show.html.erb
<h1>This is <%= @user.username %>'s page!</h1>
<%= link_to "Host an event", new_event_path %>
<%= link_to "See all events", events_path %>
<br>
<% if @user.hostings.any? %>
  <p>Hosting:</p>
  <% @user.hostings.each do |event| %>
    <h2><%= event.description %></h2>
    <h3>at: <%= event.location %></h3>
    <h4>on: <%= event.event_date %></h4>
  <% end %>
<% end %>

<br>

<% if !@upcoming_events.nil? %>
  <p>Upcoming events:</p>
  <% @upcoming_events.pluck(:description,:event_date).each do |event| %>
    <h2><%= event[0] %></h2>
    <h3><%= event[1] %></h3>
  <% end %>
<% end %>

<br>

<% if !@prev_events.nil? %>
  <p>Previous events:</p>
  <% @prev_events.pluck(:description,:event_date).each do |event| %>
    <h2><%= event[0] %></h2>
    <h3><%= event[1] %></h3>
  <% end %>
<% end %>